runtime: nodejs12
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    # catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

gcloud kms encrypt \
--plaintext-file=compute-engine-key.json \
--ciphertext-file=compute-engine-key.json22.encrypted \
--location=global \
--keyring=storage \
--key=mykey | base64